# Generated by Django 4.2.7 on 2024-04-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trains",
            name="train_number",
            field=models.IntegerField(default=0),
        ),
    ]
